### PR TITLE
Conditionally use Linux or OSX libc definitions

### LINKED ISSUE #91: Pazi does not build on OSX
The signal handler relies on the `__errno_location` function and `sa_restorer` field in libc, which isn't present in OSX apparently:

```
error[E0425]: cannot find function `__errno_location` in module `libc`
   --> /Users/lcm/.cargo/registry/src/github.com-1ecc6299db9ec823/pazi-0.1.0/src/main.rs:560:28
    |
560 |         let errno = *libc::__errno_location();
    |                            ^^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find function `__errno_location` in module `libc`
   --> /Users/lcm/.cargo/registry/src/github.com-1ecc6299db9ec823/pazi-0.1.0/src/main.rs:565:38
    |
565 |         let sigaction_errno = *libc::__errno_location();
    |                                      ^^^^^^^^^^^^^^^^ not found in `libc`

error[E0560]: struct `libc::sigaction` has no field named `sa_restorer`
   --> /Users/lcm/.cargo/registry/src/github.com-1ecc6299db9ec823/pazi-0.1.0/src/main.rs:544:13
    |
544 |             sa_restorer: None,
    |             ^^^^^^^^^^^ `libc::sigaction` does not have this field
    |
    = note: available fields are: `sa_sigaction`, `sa_mask`, `sa_flags`

error: aborting due to 5 previous errors

Some errors occurred: E0425, E0560.
For more information about an error, try `rustc --explain E0425`.
error: failed to compile `pazi v0.1.0`, intermediate artifacts can be found at `/var/folders/2x/y0sqffds2js22r895qsl3q9m0000gn/T/cargo-installqwCB3A`

Caused by:
  Could not compile `pazi`.
```

Happy to throw together a patch if you can point me at the correct way to do this kind of signal handling (or even just to move it into a linux specific function)

### PR DESCRIPTION
**Pull request by LinuxMercedes**
Fixes #91 

This works for me (x86_64 linux) and @lclarkmichalek (x86_64 OSX), so I think this change should be fine.

### CODE REVIEW

**Comment by euank** [comment]
LGTM, though to avoid regressing we should at least run build + unit tests on macOS (which travis-ci conveniently does support).

Integ might work out of the box, but building is the more important thing to make sure this doesn't regress.

**Comment by LinuxMercedes** [comment]
Oh cool, I didn't know Travis supported that. I'll fix the config here in a bit and see whether integ will run or no.

File: tests/src/integ.rs [hunk 1]
```diff
@@ -8,6 +8,14 @@ use std::thread::sleep;
 use std::time::Duration;
 use tempdir::TempDir;
 
+use std::path::Path;
+use std::borrow::Cow;
+
+fn to_canonical_string(path: &Path) -> String {
```
Comment (euank) [inline tests/src/integ.rs]: I think I'd rather canonicalize the tmpdir earlier.

Right now, the tests all begin with:

```
     let tmpdir = TempDir::new("pazi_integ").unwrap();
     let root = tmpdir.path();
```

I think we could tack on the `canonicalize` after `TmpDir....unwrap()`

If that does work, I think it seems like a cleaner fix since it cleans up the path as early as possible before other paths are joined to it.

Comment (LinuxMercedes) [reply tests/src/integ.rs]: Good call! This'll be way better.
