### PR TITLE
 main: move 'jump' and 'visit' to subcommands 

### LINKED ISSUE #70: `z init` doesn't work
This issue is suspiciously like #60, but instead of things that autosuggest to something, it's jumps that exactly match something.

This can also be seen in typing `pazi --dir init` which should look for directories containing `init`, but instead prints out help output.

### PR DESCRIPTION
**Pull request by euank**
This fixes #70.

Prior to this change, there was a mix of subcommands and flags that were
all mutually-exclusive behaviours.
This ended up being a bit awkward and made some configurations
ambiguous.

This moves to a much nicer structure. There are global flags (right now
just debug), and then there are subcommands for each distinct
mode of operation.

For ease of migration, the previous logic still remains, but it can be
safely deleted after another release or so to allow migration.

### CODE REVIEW

**Comment by euank** [comment]
After this is merged:

- [ ] File a followup issue to delete the deprecated code
- [ ] Make a v1.0.0 milestone and add the followup issue to it

File: src/main.rs [hunk 1]
```diff
@@ -90,13 +136,18 @@ fn _main() -> PaziResult {
                 .long("interactive")
                 .short("i"),
         )
+        // Deprecated in favor of .PaziSubcommand::Visit
+        // left temporarily for backwards compatibility
+        // Remove before 1.0
         .arg(
             Arg::with_name("add-dir")
```
Comment (LinuxMercedes) [inline src/main.rs]: Should this be hidden as well?

File: src/main.rs [hunk 2]
```diff
@@ -90,13 +136,18 @@ fn _main() -> PaziResult {
...
                 .help("add a directory to the frecency index")
                 .long("add-dir")
                 .takes_value(true)
                 .value_name("directory"),
         )
+        // Deprecated per above deprecations
```
Comment (LinuxMercedes) [inline src/main.rs]: Ditto here for `dir_target`

File: src/main.rs [hunk 3]
```diff
@@ -262,6 +282,183 @@ fn _main() -> PaziResult {
...
+}
+
+fn handle_print_frecency(cmd: &ArgMatches) -> PaziResult {
+    let mut frecency = load_frecency();
+
+    let matches = match cmd.value_of("dir_target") {
+        Some(to) => {
+            env::current_dir()
+                .map(|cwd| {
+                    frecency.maybe_add_relative_to(cwd, to);
```
Comment (LinuxMercedes) [inline src/main.rs]: Do we want this behavior here? It makes sense for `jump` (to help jumpstart (heh) a small database) but for `view` I'm not so sure.
